### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by wattzor** [lky1001/every-eos#1]
Hi how does this work?

- how interactive is your chart? Care to share it? 👍

**Comment by epochchaser** [comment]
Hi.
We are currently on construction.
Unfortunately, what you can see is mocking data at this time.

We will share chart logic soon.
Thank you.

**Comment by wattzor** [comment]
Thanks man! I never worked with d3 or react, just looking for a working example to reverse engineer!

Thank you keep up the good work!

**Comment by epochchaser** [comment]
I recommend you try react-stockcharts if you are looking for how to works stock.
thank you.
